spring:
  application:
    name: config-client
server:
  port: 9527

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   ## 注册中心eurka地址(用来注册到Eureka进行服务的管理)

# 关闭安全验证
management:
  security:
    enabled: false

